### ISSUE TITLE
Only black tiles

### ISSUE THREAD

**Issue by Nigcra** [the1killer/sm_overview_ahk#2]
Hi and thanks for that great idea and the realization!

I have the problem that the tiles.jpg that are created are all black. What am I doing wrong?

**Comment by Hobart2967** [comment]
Same problem here :D waited 45 min to get a fully black map

**Comment by Captnwalker1** [comment]
Black screen usually due to running in fullscreen, have to run in borderless window.

**Comment by the1killer** [comment]
Black screen is usually due to running in fullscreen, switch to borderless window mode.
